
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], variable: "--font-poppins", weight: "300" });
export const metadata = {
  title: "Hotel-booking-App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={cn(inter.className, poppins.className)} suppressHydrationWarning={true}>
          <SessionProvider>{children}</SessionProvider>
          <Toaster />
        </body>
      
    </html>
  );
}
