import Footer from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import { Inter, Poppins } from "next/font/google";
import "../globals.css";
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
const poppins = Poppins({ subsets: ["latin"], variable: "--font-poppins", weight: "300" });

export const metadata = {
  title: "Hotel-booking-App",
  description: "Generated by create next app",
};

export default async function MainLayout({ children }) {
  return (
    <SessionProvider>
      <div className={cn(inter.className, poppins.className)} suppressHydrationWarning={true}>
        <header>
          <Navbar />
        </header>

        {children}

        <Footer />
      </div>
    </SessionProvider>
  );
}
